general.import = [ "~/.config/omarchy/current/theme/alacritty.toml" ]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "Adwaita Mono" }
bold = { family = "Adwaita Mono" }
italic = { family = "Adwaita Mono" }
size = 9

[window]
padding.x = 14
padding.y = 14
decorations = "None"

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" },
{ key = "V", mods = "Control", action = "Paste" },
# Since alt and ctrl are swapped in hypr, map alt+c to SIGINT
{ key = "C", mods = "Alt", chars = "\u0003" }
]

[selection]
save_to_clipboard = true

