# All the default Omarchy aliases and functions
# (don't mess with these directly, just overwrite them here!)
source ~/.local/share/omarchy/default/bash/rc

# Add your own exports, aliases, and functions here.

bind -f ~/.inputrc

alias ll='ls -alh'
alias vult='ssh -i {{SSH_KEY}} {{SSH_USER}}@{{SSH_HOST}}'
alias dc='cd'
alias ref1='sudo reflector --country "United States" --protocol https --latest 10 --sort rate --save /etc/pacman.d/mirrorlist'
alias ref2='sudo pacman -Syy'
alias resu='sudo resolvconf -u'
alias usup='sudo wg-quick down {{VPN_CA}} 2>/dev/null; sudo wg-quick up {{VPN_US}}'
alias caup='sudo wg-quick down {{VPN_US}} 2>/dev/null; sudo wg-quick up {{VPN_CA}}'
alias alldown='sudo wg-quick down {{VPN_US}} 2>/dev/null; sudo wg-quick down {{VPN_CA}} 2>/dev/null'
alias steam='SDL_GAMECONTROLLERCONFIG="" steam &'
alias wowoff="sed -i 's/^  # kb_options = ctrl:swap/  kb_options = ctrl:swap/' ~/.config/hypr/input.conf && hyprctl reload"
alias wowon="sed -i 's/^  kb_options = ctrl:swap/  # kb_options = ctrl:swap/' ~/.config/hypr/input.conf && hyprctl reload"

# Local Dev Docker (uses docker-compose.override.yaml)
alias dbuild='docker compose build'
alias dup='docker compose up -d'
alias ddown='docker compose down'
alias dlogs='docker compose logs api'
alias dlogsf='docker compose logs -f api'
alias dps='docker compose ps'

